# Generated by Django 5.1.1 on 2024-10-11 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('rep_lname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('rep_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('address', models.CharField(max_length=250, verbose_name='Domicilio')),
                ('rep_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número Contacto')),
                ('rep_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Apoderados',
                'verbose_name_plural': 'Apoderados',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, verbose_name='Asignaturas')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('tlname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('tname', models.CharField(max_length=50, verbose_name='Nombres')),
                ('address', models.CharField(max_length=250, verbose_name='Domicilio')),
                ('tphone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Número de Contacto')),
                ('temail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('tins_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Institucional')),
            ],
            options={
                'verbose_name': 'Profesor/a',
                'verbose_name_plural': 'Profesores/as',
                'ordering': ['tlname', 'tname'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('lname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('bday', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('address', models.CharField(max_length=250, verbose_name='Domicilio')),
                ('phone', models.CharField(max_length=15, verbose_name='Número de Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('ins_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Institucional')),
                ('entry_date', models.DateField(verbose_name='Fecha de Ingreso')),
                ('actual_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentinfo.grade', verbose_name='Curso')),
                ('representative', models.ManyToManyField(to='studentinfo.representative', verbose_name='Apoderado')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
    ]
