# Generated by Django 5.1.1 on 2024-10-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('lname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('bday', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('ins_email', models.EmailField(max_length=254)),
                ('entry_date', models.DateField()),
            ],
        ),
    ]
