# Generated by Django 5.1.1 on 2024-10-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representative',
            old_name='address',
            new_name='rep_address',
        ),
    ]
