# Generated by Django 5.1.1 on 2025-01-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0002_rename_address_representative_rep_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='actual_grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='representative',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Representative',
        ),
    ]
