# Generated by Django 5.1.1 on 2024-10-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0003_alter_student_actual_grade_alter_student_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_name',
            field=models.CharField(max_length=100),
        ),
    ]
