# Generated by Django 5.1.1 on 2024-10-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0004_alter_grade_grade_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentinfo.representative', verbose_name='Apoderado'),
        ),
    ]
