# Generated by Django 5.1.1 on 2024-10-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0005_representative_student_representative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='representative',
        ),
        migrations.AddField(
            model_name='student',
            name='representative',
            field=models.ManyToManyField(blank=True, to='studentinfo.representative', verbose_name='Apoderado'),
        ),
    ]
