# Generated by Django 5.1.1 on 2024-10-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0006_remove_student_representative_student_representative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representative',
            name='description',
        ),
        migrations.AddField(
            model_name='representative',
            name='rep_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='representative',
            name='rep_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='representative',
            name='rep_lname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='representative',
            name='rep_phone',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Número Contacto'),
        ),
        migrations.AddField(
            model_name='representative',
            name='rep_rut',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='rep_name',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='Nombres'),
        ),
    ]
