# Generated by Django 5.1.1 on 2024-10-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0007_remove_representative_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='rep_rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Rut'),
        ),
    ]
