# Generated by Django 5.1.1 on 2024-10-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0008_alter_representative_rep_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='rep_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número Contacto'),
        ),
    ]
