# Generated by Django 5.1.1 on 2024-10-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0009_alter_representative_rep_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, verbose_name='Asignaturas')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trut', models.CharField(max_length=12, unique=True)),
                ('tlname', models.CharField(max_length=20, verbose_name='Apellidos')),
                ('tname', models.CharField(max_length=20, verbose_name='Nombres')),
                ('tphone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Número de Contacto')),
                ('temail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='representative',
            name='rep_rut',
        ),
        migrations.AlterField(
            model_name='representative',
            name='rep_lname',
            field=models.CharField(default='0000000000-0', max_length=50, unique=True, verbose_name='Apellidos'),
        ),
    ]
