# Generated by Django 5.1.1 on 2024-10-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0010_subjects_teacher_remove_representative_rep_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='rep_rut',
            field=models.CharField(default='0000000000-0', max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='rep_lname',
            field=models.CharField(max_length=50, unique=True, verbose_name='Apellidos'),
        ),
    ]
