# Generated by Django 5.1.1 on 2024-10-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0011_representative_rep_rut_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
