# Generated by Django 5.1.1 on 2025-01-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NOMBRE')),
                ('last_name', models.CharField(max_length=50, verbose_name='APELLIDOS')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT (sin puntos, solo guión)')),
                ('birth_day', models.DateField(verbose_name='FECHA DE NACIMIENTO')),
                ('address', models.CharField(max_length=50, verbose_name='DIRECCIÓN')),
                ('city', models.CharField(max_length=50, verbose_name='CIUDAD')),
                ('enrollment_date', models.DateField(verbose_name='FECHA DE INGRESO')),
                ('grade', models.CharField(choices=[('1B', '1ro Básico'), ('2B', '2do Básico'), ('3B', '3ro Básico'), ('4B', '4to Básico'), ('5B', '5to Básico'), ('6B', '6to Básico'), ('7B', '7mo Básico'), ('8B', '8vo Básico'), ('1M', '1ro Medio'), ('2M', '2do Medio'), ('3M', '3ro Medio'), ('4M', '4to Medio')], max_length=3, verbose_name='CURSO')),
                ('institutional_email', models.EmailField(blank=True, max_length=254, verbose_name='CORREO ELECTRÓNICO INSTITUCIONAL (opcional)')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
    ]
