# Generated by Django 5.1.1 on 2025-01-21 17:16

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('academic_degree', models.CharField(max_length=50, verbose_name='Título Académido')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Número Telefónico (opcional)')),
            ],
        ),
    ]
