# Generated by Django 5.1.1 on 2025-01-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
    ]
