# Generated by Django 5.1.1 on 2025-01-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Número Telefónico (opcional)'),
        ),
    ]
